// 此文件由 tool/sync_app_metadata.dart 从 app_metadata.json 生成，请勿手工修改。 元数据指纹：ew0KICAicHJvamVjdE5hbWUiOiAibHVtYSIsDQogICJkaXNwbGF5TmFtZSI6ICLovbvlvbEiLA0KICAicHJvZHVjdE5hbWUiOiAi6L275b2xIEx1bWEiLA0KICAiYW5kcm9pZEFwcGxpY2F0aW9uSWQiOiAiY29tLnhpbmdoZTk4Lmx1bWEiLA0KICAid2luZG93c0V4ZWN1dGFibGVOYW1lIjogImx1bWEiLA0KICAiY29tcGFueU5hbWUiOiAiTHVtYSIsDQogICJhdXRob3JOYW1lIjogInhpbmdoZTk4IiwNCiAgImNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMjYgY29tLnhpbmdoZTk4LiBBbGwgcmlnaHRzIHJlc2VydmVkLiIsDQogICJ2ZXJzaW9uIjogIjEuMS4wKzEiDQp9
#pragma once

#define LUMA_WINDOW_TITLE L"轻影 Luma"
#define LUMA_COMPANY_NAME "Luma"
#define LUMA_FILE_DESCRIPTION "轻影 Luma"
#define LUMA_INTERNAL_NAME "luma"
#define LUMA_LEGAL_COPYRIGHT "Copyright (C) 2026 com.xinghe98. All rights reserved."
#define LUMA_ORIGINAL_FILENAME "luma.exe"
#define LUMA_PRODUCT_NAME "轻影 Luma"
